### ISSUE TITLE
txt文件提交的格式是什么？

### ISSUE THREAD

**Issue by xxddccaa** [AItransCompetition/DDoS-Detection-Challenge#1]
![image](https://github.com/AItransCompetition/DDoS-Detection-Challenge/assets/25652821/73e46738-9186-49d7-9bbb-2ece16a50cb0)

第一行数字，其他行是标签？
需要flowID吗，需要的话，网页上不支持上传那么大的txt文件。

**Comment by dejian-lc** [comment]
是按照标签样式提交吗，怎么我提交都是分数都是0

**Comment by xxddccaa** [comment]
> 是按照标签样式提交吗，怎么我提交都是分数都是0

第一行是flowid数量，后面就是一行一个flowid，而且是去重之后的flowid

**Comment by dejian-lc** [comment]
谢谢好心人，之前没有去重操作，我看示例代码里面是取大于阈值的，终于通过了，差点弃赛了

**Comment by xxddccaa** [comment]
> 谢谢好心人，之前没有去重操作，我看示例代码里面是取大于阈值的，终于通过了，差点弃赛了

没事噢，我做到后面也不会了
